### ISSUE TITLE
Reputation System

### ISSUE THREAD

**Issue by jclinkinbeard** [bclinkinbeard/pricer-discord-bot#3]
Reputation example

!addrep @jack good prices
!-rep @jack bad prices

@jack: !rep
Response from bot shows
Positive Rep: 1
Negative Rep: 1
“good prices”
“bad prices”

!-rep command adds a negative rep, and also sends some sort of message @Administrator please validate this -rep
If the -rep is fine and deserved, then nothing happens
If it isnt deserved the administrator can use !clear rep -1 @jack
That removes a negative rep from the user

**Comment by bclinkinbeard** [comment]
`!addrep`, `!badrep`, and `!rep` all functional. Need to prevent people from giving themselves rep.

**Comment by bclinkinbeard** [comment]
Add a `!toprep` command that shows top 10 positive repo users and their counts

**Comment by bclinkinbeard** [comment]
Clear bad rep via reaction by admin

**Comment by bclinkinbeard** [comment]
This is all done, right?
